In [1]:
import pandas as pd

df = pd.read_csv("creditcard.csv")
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
# df.info()
df.describe()

Time            V1            V2            V3            V4  \
count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean    94813.859575  1.175161e-15  3.384974e-16 -1.379537e-15  2.094852e-15   
std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00   
min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00   
25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01   
50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02   
75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01   
max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01   

                 V5            V6            V7            V8            V9  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   1.021879e-15  1.494498e-15 -5.620335e-16  1.149614e-16 -2.414189e-15   
std    1.380247e+00  1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00   
min   -1.137433e+02 -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01   
25%   -6.915971e-01 -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01   
50%   -5.433583e-02 -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02   
75%    6.119264e-01  3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01   
max    3.480167e+01  7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01   

       ...           V21           V22           V23           V24  \
count  ...  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   ...  1.628620e-16 -3.576577e-16  2.618565e-16  4.473914e-15   
std    ...  7.345240e-01  7.257016e-01  6.244603e-01  6.056471e-01   
min    ... -3.483038e+01 -1.093314e+01 -4.480774e+01 -2.836627e+00   
25%    ... -2.283949e-01 -5.423504e-01 -1.618463e-01 -3.545861e-01   
50%    ... -2.945017e-02  6.781943e-03 -1.119293e-02  4.097606e-02   
75%    ...  1.863772e-01  5.285536e-01  1.476421e-01  4.395266e-01   
max    ...  2.720284e+01  1.050309e+01  2.252841e+01  4.584549e+00   

                V25           V26           V27           V28         Amount  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  284807.000000   
mean   5.109395e-16  1.686100e-15 -3.661401e-16 -1.227452e-16      88.349619   
std    5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01     250.120109   
min   -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01       0.000000   
25%   -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.295979e-02       5.600000   
50%    1.659350e-02 -5.213911e-02  1.342146e-03  1.124383e-02      22.000000   
75%    3.507156e-01  2.409522e-01  9.104512e-02  7.827995e-02      77.165000   
max    7.519589e+00  3.517346e+00  3.161220e+01  3.384781e+01   25691.160000   

               Class  
count  284807.000000  
mean        0.001727  
std         0.041527  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000  

[8 rows x 31 columns]

In [10]:
import seaborn as sns
import matplotlib.pyplot as plt
df_heatmap = df.drop(columns=['Time', 'Amount'])
matrix_df = df_heatmap.corr()
# plt.figure(figsize=(20, 20))
# sns.heatmap(matrix_df, annot=True, cmap="coolwarm", fmt='.2f', square=True)

In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

X = df.drop(columns=['Class'])
y = df['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, max_depth=10, class_weight='balanced')
rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_test)

print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9994
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.82      0.83      0.82        98

    accuracy                           1.00     56962
   macro avg       0.91      0.91      0.91     56962
weighted avg       1.00      1.00      1.00     56962

Confusion Matrix:
[[56846    18]
 [   17    81]]


In [19]:
import xgboost as xgb

xgb_model = xgb.XGBClassifier(n_estimators=100, learning_rate=0.1, random_state=42, max_depth=6, eval_metric='aucpr')
xgb_model.fit(X_train, y_train)
y_pred = xgb_model.predict(X_test)

print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

y_probs = xgb_model.predict_proba(X_test)[:, 1]
threshold = 0.3
y_pred_new = (y_probs > threshold).astype(int)
print(f"Accuracy: {accuracy_score(y_test, y_pred_new):.4f}")
print("Classification Report:")
print(classification_report(y_test, y_pred_new))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_new))

Accuracy: 0.9995
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.92      0.78      0.84        98

    accuracy                           1.00     56962
   macro avg       0.96      0.89      0.92     56962
weighted avg       1.00      1.00      1.00     56962

Confusion Matrix:
[[56857     7]
 [   22    76]]
Accuracy: 0.9995
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.90      0.81      0.85        98

    accuracy                           1.00     56962
   macro avg       0.95      0.90      0.92     56962
weighted avg       1.00      1.00      1.00     56962

Confusion Matrix:
[[56855     9]
 [   19    79]]


In [16]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# 準備數據
X = df.drop(columns=['Class'])
y = df['Class']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 計算 scale_pos_weight
scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
print(f"scale_pos_weight = {scale_pos_weight:.2f}")

# XGBoost 模型
xgb_model = xgb.XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    use_label_encoder=False,
    eval_metric='aucpr'  # 使用 PR-AUC 作為評估指標，更適合不平衡數據
)

xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)
print("\nXGBoost 結果：")
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

scale_pos_weight = 577.29


c:\Users\peter\python_workstation\python_practice\python_practice_data_processing\.venv\Lib\site-packages\xgboost\training.py:199: UserWarning: [10:33:48] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)



XGBoost 結果：
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.88      0.84      0.86        98

    accuracy                           1.00     56962
   macro avg       0.94      0.92      0.93     56962
weighted avg       1.00      1.00      1.00     56962

[[56853    11]
 [   16    82]]


In [32]:
# 獲取預測機率
y_pred_proba = rf_model.predict_proba(X_test)[:, 1]

# 嘗試不同閾值
for threshold in [0.5, 0.4, 0.3, 0.2]:
    y_pred_custom = (y_pred_proba >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred_custom).ravel()
    recall = tp / (tp + fn)
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    print(f"閾值 {threshold}: Recall={recall:.3f}, Precision={precision:.3f}, FN={fn}, FP={fp}")

y_probs = rf_model.predict_proba(X_test)[:, 1]
threshold = 0.3
y_pred_new = (y_probs > threshold).astype(int)
print(f"Accuracy: {accuracy_score(y_test, y_pred_new):.4f}")
print("Classification Report:")
print(classification_report(y_test, y_pred_new))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_new))

閾值 0.5: Recall=0.827, Precision=0.818, FN=17, FP=18
閾值 0.4: Recall=0.847, Precision=0.709, FN=15, FP=34
閾值 0.3: Recall=0.878, Precision=0.593, FN=12, FP=59
閾值 0.2: Recall=0.888, Precision=0.377, FN=11, FP=144
Accuracy: 0.9988
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.59      0.88      0.71        98

    accuracy                           1.00     56962
   macro avg       0.80      0.94      0.85     56962
weighted avg       1.00      1.00      1.00     56962

Confusion Matrix:
[[56805    59]
 [   12    86]]


In [29]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

# 假設你的測試集有 Amount 欄位
# X_test 包含 Amount，我們需要提取它
X = df.drop(columns=['Class'])
y = df['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 訓練模型並獲取預測機率
rf_model.fit(X_train, y_train)
y_pred_proba = rf_model.predict_proba(X_test)[:, 1]

# 提取測試集的交易金額
amounts = X_test['Amount'].values

# 定義成本參數
COST_FP = 10  # 每筆誤報的人工審核成本（美元）
COST_FN_MULTIPLIER = 1.0  # FN 成本 = 詐欺金額 × 乘數（可設 1.0 = 損失全額）

def calculate_total_cost(y_true, y_pred, amounts, cost_fp=10, fn_multiplier=1.0):
    """計算總成本"""
    # 找出 FP 和 FN 的索引
    fp_mask = (y_pred == 1) & (y_true == 0)  # 預測詐欺，實際正常
    fn_mask = (y_pred == 0) & (y_true == 1)  # 預測正常，實際詐欺
    
    # 計算成本
    fp_cost = fp_mask.sum() * cost_fp
    fn_cost = (amounts[fn_mask] * fn_multiplier).sum()  # 漏掉的詐欺金額
    
    total_cost = fp_cost + fn_cost
    return total_cost, fp_cost, fn_cost, fp_mask.sum(), fn_mask.sum()

# 測試不同閾值，找出最低成本的閾值
thresholds = np.arange(0.05, 0.95, 0.05)
results = []



for threshold in thresholds:
    y_pred_custom = (y_pred_proba >= threshold).astype(int)
    total, fp_cost, fn_cost, fp_count, fn_count = calculate_total_cost(
        y_test.values, y_pred_custom, amounts, COST_FP, COST_FN_MULTIPLIER
    )
    
    # 計算 Precision 和 Recall
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred_custom).ravel()
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0
    
    results.append({
        'threshold': threshold,
        'total_cost': total,
        'fp_cost': fp_cost,
        'fn_cost': fn_cost,
        'fp_count': fp_count,
        'fn_count': fn_count,
        'precision': precision,
        'recall': recall
    })

results_df = pd.DataFrame(results)

# 找出最低成本的閾值
best_row = results_df.loc[results_df['total_cost'].idxmin()]
print("=" * 60)
print("📊 成本敏感分析結果")
print("=" * 60)
print(f"\n🎯 最佳閾值: {best_row['threshold']:.2f}")
print(f"💰 最低總成本: ${best_row['total_cost']:,.2f}")
print(f"   - FP 成本: ${best_row['fp_cost']:,.2f} ({int(best_row['fp_count'])} 筆誤報)")
print(f"   - FN 成本: ${best_row['fn_cost']:,.2f} ({int(best_row['fn_count'])} 筆漏掉)")
print(f"📈 Precision: {best_row['precision']:.3f}")
print(f"📈 Recall: {best_row['recall']:.3f}")

# 顯示完整表格
print("\n" + "=" * 60)
print("📋 不同閾值的成本比較")
print("=" * 60)
print(results_df.to_string(index=False))

📊 成本敏感分析結果

🎯 最佳閾值: 0.40
💰 最低總成本: $2,361.77
   - FP 成本: $340.00 (34 筆誤報)
   - FN 成本: $2,021.77 (15 筆漏掉)
📈 Precision: 0.709
📈 Recall: 0.847

📋 不同閾值的成本比較
 threshold  total_cost  fp_cost  fn_cost  fp_count  fn_count  precision   recall
      0.05    22613.71    21320  1293.71      2132         9   0.040072 0.908163
      0.10     8042.71     6220  1822.71       622        10   0.123944 0.897959
      0.15     4502.71     2680  1822.71       268        10   0.247191 0.897959
      0.20     3266.50     1440  1826.50       144        11   0.376623 0.887755
      0.25     2686.50      860  1826.50        86        11   0.502890 0.887755
      0.30     2427.89      590  1837.89        59        12   0.593103 0.877551
      0.35     2460.77      440  2020.77        44        14   0.656250 0.857143
      0.40     2361.77      340  2021.77        34        15   0.709402 0.846939
      0.45     4061.45      230  3831.45        23        16   0.780952 0.836735
      0.50     4273.32      180  4093.

In [23]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt

# 成本參數（實務修正版）
COST_FP = 15  # 每筆誤報的審核成本（美元）
FN_MULTIPLIER_OPTIONS = [1, 5, 10, 30, 50, 100]  # 不同的 FN 成本乘數

def calculate_total_cost(y_true, y_pred, amounts, cost_fp=15, fn_multiplier=10):
    """計算總成本（實務版本）"""
    fp_mask = (y_pred == 1) & (y_true == 0)
    fn_mask = (y_pred == 0) & (y_true == 1)
    
    fp_cost = fp_mask.sum() * cost_fp
    fn_cost = (amounts[fn_mask] * fn_multiplier).sum()
    
    return fp_cost + fn_cost, fp_cost, fn_cost, fp_mask.sum(), fn_mask.sum()

# 準備數據
X = df.drop(columns=['Class'])
y = df['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
amounts = X_test['Amount'].values

# 訓練模型
rf_model.fit(X_train, y_train)
y_pred_proba = rf_model.predict_proba(X_test)[:, 1]

# 分析不同 FN 乘數的影響
print("=" * 80)
print("📊 FN 成本乘數對最佳閾值的影響分析")
print("=" * 80)
print(f"{'FN 乘數':>10} | {'最佳閾值':>10} | {'Total Cost':>14} | {'Recall':>8} | {'Precision':>10} | {'FN Count':>8}")
print("-" * 80)

thresholds = np.arange(0.01, 0.99, 0.01)
best_results = []

for fn_mult in FN_MULTIPLIER_OPTIONS:
    best_threshold = None
    best_total_cost = float('inf')
    best_metrics = {}
    
    for threshold in thresholds:
        y_pred_custom = (y_pred_proba >= threshold).astype(int)
        total, fp_cost, fn_cost, fp_count, fn_count = calculate_total_cost(
            y_test.values, y_pred_custom, amounts, COST_FP, fn_mult
        )
        
        if total < best_total_cost:
            best_total_cost = total
            best_threshold = threshold
            tn, fp, fn, tp = confusion_matrix(y_test, y_pred_custom).ravel()
            best_metrics = {
                'precision': tp / (tp + fp) if (tp + fp) > 0 else 0,
                'recall': tp / (tp + fn) if (tp + fn) > 0 else 0,
                'fn_count': fn,
                'fp_count': fp
            }
    
    best_results.append({
        'fn_mult': fn_mult,
        'threshold': best_threshold,
        'total_cost': best_total_cost,
        'recall': best_metrics['recall'],
        'precision': best_metrics['precision'],
        'fn_count': best_metrics['fn_count']
    })
    
    print(f"{fn_mult:>10}x | {best_threshold:>10.2f} | ${best_total_cost:>13,.2f} | {best_metrics['recall']:>8.3f} | {best_metrics['precision']:>10.3f} | {best_metrics['fn_count']:>8}")

print("-" * 80)
print("\n💡 觀察：FN 乘數越高，最佳閾值越低 → Recall 越高、Precision 越低")

📊 FN 成本乘數對最佳閾值的影響分析
     FN 乘數 |       最佳閾值 |     Total Cost |   Recall |  Precision | FN Count
--------------------------------------------------------------------------------
         1x |       0.44 | $     2,381.77 |    0.847 |      0.776 |       15
         5x |       0.30 | $    10,074.45 |    0.878 |      0.593 |       12
        10x |       0.30 | $    19,263.90 |    0.878 |      0.593 |       12
        30x |       0.08 | $    52,746.30 |    0.908 |      0.087 |        9
        50x |       0.08 | $    78,620.50 |    0.908 |      0.087 |        9
       100x |       0.04 | $   125,261.00 |    0.918 |      0.027 |        8
--------------------------------------------------------------------------------

💡 觀察：FN 乘數越高，最佳閾值越低 → Recall 越高、Precision 越低
